### ISSUE TITLE
Documentation: Update Patra README.md file

### ISSUE THREAD

**Issue by starvader13** [starvader13/Patra#32]
A README.md file needs to have different sections. Currently, it only has an Introduction Section.

These sections should be included for a better understanding of the project ;
- [x] Getting Started
    - [x] Prerequisites
    - [x] Installation 
    - [x] Tech Stack
- [x] Documentation Reference 
- [x] LICENSE

For reference, you can look up at: https://github.com/starvader13/Udemy-Backend/blob/main/README.md

**Comment by singharpitt** [comment]
Assign this to me !
